### ISSUE TITLE
Binary background looks too sharp to the eye

### ISSUE THREAD

**Issue by ghost** [mtkacodersunite/old-website#4]
The binary background simply looks too sharp. A solution would be to **zoom in the image,** or **replace it with an entirely new one.**

**Comment by eado** [comment]
I disagree, but that's my opinion.

**Comment by ghost** [comment]
Yeah, I guess different people have different preferences. The 0 digits' sharp edges just look too sharp, I guess. Heh.

**Comment by jackwherry** [comment]
It might be something to do with my browser and screen resolution, but I am finding the opposite effect to show. It appears that the edges of some of the components have the "staircase" effect, a telltale sign of it being a bitmap. Now that I change devices, it looks sharper on an HiDPI/Retina display.

**Comment by ghost** [comment]
That's a problem. It should look the same for mobile viewers and PC viewers. If anything, we should make it 4k or vectorize. Luckily, resizing it with Photoshop is possible.
