### ISSUE TITLE
Logotype scales with screen width too much

### ISSUE THREAD

**Issue by jackwherry** [mtkacodersunite/old-website#5]
When you adjust the screen width, the logotype scales down more than it should, eventually becoming the same size as the navlinks. We need to decrease the scaling multiplier. 

Specifically, it looks really weird at simulated and real mobile screen sizes (portrait, obviously).

**Comment by eado** [comment]
It isn't necessarily a bug.

**Comment by eado** [comment]
This should fix it:
[Commit Link](https://github.com/mtkacodersunite/mtkacodersunite.github.io/commit/6f24e1024b017c4d2c0fdab9ba6f975f4b926c6c)

**Comment by eado** [comment]
Now it should fix it.
